import test from 'node:test';import assert from 'node:assert/strict';
import {Engine,evaluate,zats,validateConfig} from '../lib/engine.mjs';
const address='u1'+'a'.repeat(100),to='u1'+'b'.repeat(100),txid='c'.repeat(64);
function config(){return {address,quantity:1,maxPrice:'0.02',maxFee:'0.001',expiresAt:Date.now()+3600000};}
function state(){return {network:'main',now:Date.now(),address,round:{audience:'public',state:'live',start:Date.now()-10000,end:null},rounds:[],remaining:3,left:100,limit:3,soldOut:false,canMint:true,free:false,watched:true,price:'0.02',payTo:to,memo:'mint '+address};}
function fixture(overrides={}){let sends=0,claims=0,saved=0;let current=state();const journal={tasks:[]};const wallet={check:async()=>{},propose:async()=>({fee:10000}),confirm:async()=>{sends++;return {txids:[txid]};}};const site={state:async()=>structuredClone(current),progress:async()=>({txid,steps:[{key:'issued',done:true}]}),claim:async()=>{claims++;return {ok:true,face:1};}};
 const e=new Engine({site,wallet,journal,persist:async()=>{saved++;},...overrides});return {e,wallet,site,journal,set:s=>current=s,sends:()=>sends,claims:()=>claims,saved:()=>saved};}
test('amount parsing is exact; malformed amounts rejected',()=>{assert.equal(zats('0.00000001'),1n);assert.equal(zats('0.02'),2000000n);for(const x of ['1e-2','-1','0.000000001','NaN',' 1','Infinity','21000001'])assert.throws(()=>zats(x));});
test('limits and expiry validated',()=>{assert.throws(()=>validateConfig({...config(),quantity:4}));assert.throws(()=>validateConfig({...config(),expiresAt:0}));});
test('whitelist never pays',async()=>{const f=fixture();f.set({...state(),round:{audience:'whitelist',state:'live'}});await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);assert.equal(f.e.task.status,'waiting');});
test('matching public state pays once then issuance confirms separately',async()=>{const f=fixture();await f.e.arm(config());await Promise.all([f.e.tick(),f.e.tick(),f.e.tick()]);assert.equal(f.sends(),1);assert.equal(f.e.task.status,'broadcast');assert.ok(f.saved()>=3);await f.e.tick();assert.equal(f.e.task.status,'done');await f.e.tick();assert.equal(f.sends(),1);});
test('public label alone is not permission',()=>{assert.equal(evaluate({...state(),canMint:false},config()),null);assert.equal(evaluate({...state(),round:{audience:'public',state:'upcoming'}},config()),null);});
for(const [name,change] of Object.entries({watcher:{watched:false},price:{price:'0.03'},memo:{memo:'mint someone-else'},destination:{payTo:'t1bad'},network:{network:'test'},address:{address:'u1wrong'},soldout:{soldOut:true},quota:{remaining:0}}))test(name+' fails closed',async()=>{const f=fixture();f.set({...state(),...change});await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);assert.equal(f.e.task.status,'stopped');});
test('fee cap enforced before confirmation',async()=>{const f=fixture();f.wallet.propose=async()=>({fee:200000});await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);assert.equal(f.e.task.status,'stopped');});
test('invoice changes during preparation do not pay',async()=>{const f=fixture();let n=0;f.site.state=async()=>({...state(),price:++n>1?'0.01':'0.02'});await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);});
test('stop during slow proposal prevents payment',async()=>{const f=fixture();f.wallet.propose=async()=>{await f.e.stop();return {fee:10000};};await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);});
test('uncertain broadcast is never repeated',async()=>{const f=fixture();let calls=0;f.wallet.confirm=async()=>{calls++;throw new Error('timeout');};await f.e.arm(config());await f.e.tick();await f.e.tick();assert.equal(calls,1);assert.equal(f.e.task.status,'unknown');await assert.rejects(f.e.arm(config()));});
test('crash journal remains blocked',async()=>{const j={tasks:[{config:config(),status:'sending',attempts:[{}]}]};const f=fixture({journal:j});assert.equal(j.tasks[0].status,'unknown');await assert.rejects(f.e.arm(config()));});
test('failed durable write never triggers payment',async()=>{const f=fixture();await f.e.arm(config());f.e.persist=async()=>{throw new Error('disk full');};await assert.rejects(f.e.tick());await f.e.tick();assert.equal(f.sends(),0);assert.equal(f.e.active,false);});
test('another transfer or tx receipt cannot mark issuance',async()=>{const f=fixture();f.site.progress=async()=>({txid:'d'.repeat(64),held:100,steps:[{key:'issued',done:true}]});await f.e.arm(config());await f.e.tick();await f.e.tick();assert.equal(f.e.task.status,'broadcast');});
test('two mints are serialized after project receipt',async()=>{const f=fixture();await f.e.arm({...config(),quantity:2});await f.e.tick();assert.equal(f.sends(),1);await f.e.tick();assert.equal(f.sends(),1);await f.e.tick();assert.equal(f.sends(),2);await f.e.tick();assert.equal(f.e.task.status,'done');});
test('free claim stays within public flow',async()=>{const f=fixture();f.set({...state(),price:'0',free:true,payTo:'',memo:''});await f.e.arm(config());await f.e.tick();assert.equal(f.sends(),0);assert.equal(f.claims(),1);assert.equal(f.e.task.status,'done');});
test('concurrent arm requests cannot create two active tasks',async()=>{const f=fixture();const r=await Promise.allSettled([f.e.arm(config()),f.e.arm(config())]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.journal.tasks.length,1);});
test('stopping after an attempt cannot bypass duplicate guard',async()=>{const f=fixture();await f.e.arm(config());await f.e.tick();await f.e.stop();f.e.task.status='stopped';await assert.rejects(f.e.arm(config()));});
