import test from 'node:test';import assert from 'node:assert/strict';import {setupNoir} from '../public/noir-ui.js';
const address='u1'+'a'.repeat(100),transparent='t1'+'A'.repeat(33),txid='f'.repeat(64);
function env(){const ids=new Map(),requests=[],apis=[],listeners={};let failSend=false;const $=id=>{if(!ids.has(id))ids.set(id,{value:'',checked:false,disabled:false,textContent:'',innerHTML:'',addEventListener:()=>{}});return ids.get(id);};$('#noirprice').value='0.02';$('#noirfee').value='0.001';$('#noirhours').value='24';$('#noirfunding').value='transparent';const provider={on:(key,fn)=>listeners[key]=fn,request:async x=>{requests.push(x);if(/Accounts$/.test(x.method))return {shielded:address,transparent};if(x.method==='zcash_getBalance')return {transparent:'0.09939',shielded:'0'};if(x.method==='zcash_getMaxTransfer')return {fee:'0.0001',maxAmount:'0.09'};if(x.method==='zcash_sendTransaction'){if(failSend)throw Error('rejected');return txid;}throw Error('unexpected');}};
 const old={window:globalThis.window,document:globalThis.document,setInterval:globalThis.setInterval};globalThis.window={noirwallet:{zcash:provider},addEventListener:()=>{}};globalThis.document={dispatchEvent:()=>{}};const timers=[];globalThis.setInterval=f=>{timers.push(f);return 1;};let c;
 const api=async(path,b)=>{apis.push({path,b});if(path==='noir/quote'){c=b;return {ready:true,id:'quote',config:c,invoice:{to:'u1'+'c'.repeat(100),memo:'mint '+address,price:'0.02'}};}if(path==='noir/begin')return {taskId:'task',config:c,invoice:{to:'u1'+'c'.repeat(100),memo:'mint '+address,price:'0.02'}};return {ok:true};};const paint=setupNoir({api,$,say:()=>{}});
 return {$,requests,apis,provider,timers,paint,listeners,fail:()=>failSend=true,restore:()=>{for(const [k,v] of Object.entries(old)){if(v===undefined)delete globalThis[k];else globalThis[k]=v;}}};}
test('Noir UI connection and balance reads do not arm or send, unchecked consent blocks arm',async()=>{const f=env();try{await f.$('#noirconnect').onclick();assert.match(f.$('#noiraccount').innerHTML,/0.09939/);assert.equal(f.apis.length,0);assert(!f.requests.some(x=>x.method==='zcash_sendTransaction'));await f.$('#noirwait').onclick();assert.match(f.$('#noirstatus').textContent,/勾选/);assert.equal(f.apis.length,0);}finally{f.restore();}});
test('consented Noir wait records intent before a single send and reports receipt',async()=>{const f=env();try{await f.$('#noirconnect').onclick();f.$('#noirconsent').checked=true;await f.$('#noirwait').onclick();assert.deepEqual(f.apis.map(x=>x.path),['noir/quote','noir/begin','noir/report']);assert.equal(f.apis.at(-1).b.txid,txid);assert.equal(f.requests.filter(x=>x.method==='zcash_sendTransaction').length,1);for(const timer of f.timers)timer();assert.equal(f.requests.filter(x=>x.method==='zcash_sendTransaction').length,1);assert.match(f.$('#noirstatus').textContent,/等待 ZADDR/);}finally{f.restore();}});
test('Noir rejection is reported as uncertain and polling never resends',async()=>{const f=env();try{await f.$('#noirconnect').onclick();f.fail();f.$('#noirconsent').checked=true;await f.$('#noirwait').onclick();assert.equal(f.apis.at(-1).path,'noir/report');assert.equal(f.apis.at(-1).b.txid,undefined);for(const timer of f.timers)timer();assert.equal(f.requests.filter(x=>x.method==='zcash_sendTransaction').length,1);assert.match(f.$('#noirstatus').textContent,/不会自动重发/);}finally{f.restore();}});
test('account change invalidates UI connection and consent',async()=>{const f=env();try{await f.$('#noirconnect').onclick();f.$('#noirconsent').checked=true;f.listeners.accountsChanged();await f.$('#noirwait').onclick();assert.match(f.$('#noirstatus').textContent,/先连接/);assert.equal(f.apis.length,0);assert.equal(f.$('#noirconsent').checked,false);}finally{f.restore();}});
