import test from 'node:test';import assert from 'node:assert/strict';
import {NoirPayments} from '../lib/noir-payments.mjs';
import {currentAccount,checkNoir,sendNoir} from '../public/noir-provider.js';
const address='u1'+'a'.repeat(100),transparent='t1'+'A'.repeat(33),to='u1'+'a'.repeat(99)+'c',txid='c'.repeat(64);
const config=()=>({address,maxPrice:'0.02',maxFee:'0.001',fundingSource:'transparent',expiresAt:Date.now()+60000});
const state=()=>({network:'main',now:Date.now(),address,round:{audience:'public',state:'live',start:Date.now()-10000,end:null},rounds:[],remaining:3,left:100,limit:3,soldOut:false,canMint:true,free:false,watched:true,price:'0.02',payTo:to,memo:'mint '+address});
function fixture(){let current=state(),saved=0;const journal={tasks:[]},site={state:async()=>structuredClone(current),progress:async()=>({txid,steps:[{key:'issued',done:true}]})};const n=new NoirPayments({site,journal,persist:async()=>saved++});return {n,site,journal,set:s=>current=s,saved:()=>saved};}
function provider(){const calls=[];return {calls,request:async o=>{calls.push(o);if(o.method==='zcash_getAccounts')return {shielded:address,transparent};if(o.method==='zcash_getMaxTransfer')return {maxAmount:'0.09',fee:'0.0001'};if(o.method==='zcash_sendTransaction')return txid;throw Error('unexpected method');}};}
test('Noir can quote its own receiving address without starting Zingo; no payment at quote',async()=>{const f=fixture();const q=await f.n.quote(config());assert(q.ready);assert.equal(f.journal.tasks.length,0);assert.equal(q.config.fundingSource,'transparent');});
test('whitelist, upcoming Public and no canMint only wait',async()=>{for(const patch of [{round:{audience:'whitelist',state:'live'}},{round:{audience:'public',state:'upcoming'}},{canMint:false}]){const f=fixture();f.set({...state(),...patch});assert.equal((await f.n.quote(config())).ready,false);assert.equal(f.journal.tasks.length,0);}});
test('begin rechecks invoice and disallows changed memo, price, supply and expiry',async()=>{for(const patch of [{memo:'mint different '+address},{price:'0.01'},{left:0},{round:{audience:'public',state:'done'}}]){const f=fixture(),q=await f.n.quote(config());f.set({...state(),...patch});await assert.rejects(f.n.begin(q.id));assert.equal(f.journal.tasks.length,0);}});
test('a quote authorizes only one durable attempt even across concurrent browser tabs',async()=>{const f=fixture();const q1=await f.n.quote(config()),q2=await f.n.quote(config());const r=await Promise.allSettled([f.n.begin(q1.id),f.n.begin(q2.id)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.journal.tasks.length,1);assert.equal(f.saved(),1);await assert.rejects(f.n.quote(config()));});
test('no browser ticket returned when persistence fails',async()=>{const f=fixture();const q=await f.n.quote(config());f.n.persist=async()=>{throw Error('disk full');};await assert.rejects(f.n.begin(q.id));await assert.rejects(f.n.quote(config()));});
test('quote expiry and other wallet running prevent Noir attempts',async()=>{const f=fixture();const q=await f.n.quote(config());f.n.quotes.get(q.id).at=0;await assert.rejects(f.n.begin(q.id));f.n.otherBusy=()=>true;await assert.rejects(f.n.quote(config()));});
test('uncertain requests stay blocked and matching receipt is required for issuance',async()=>{const f=fixture(),q=await f.n.quote(config()),ticket=await f.n.begin(q.id);await f.n.report(ticket.taskId);assert.equal(f.journal.tasks[0].status,'unknown');await assert.rejects(f.n.quote(config()));await f.n.report(ticket.taskId,txid);await assert.rejects(f.n.report(ticket.taskId,'d'.repeat(64)));f.site.progress=async()=>({txid:'d'.repeat(64),steps:[{key:'issued',done:true}]});assert.equal((await f.n.progress(ticket.taskId)).status,'broadcast');f.site.progress=async()=>({txid,steps:[{key:'issued',done:true}]});assert.equal((await f.n.progress(ticket.taskId)).status,'done');});
test('mainnet address pair, source and decimal limits are checked',async()=>{assert.deepEqual(currentAccount({shielded:address,transparent}),{address,transparent});for(const raw of [null,{shielded:'utest1abc',transparent},{shielded:address,transparent:'tmtest'}])assert.throws(()=>currentAccount(raw));const f=fixture();await assert.rejects(f.n.quote({...config(),fundingSource:'auto'}));await assert.rejects(f.n.quote({...config(),maxPrice:'1e-2'}));});
test('Noir estimate checks selected funding pool, memo and fee cap before requesting payment',async()=>{const p=provider();const invoice={to,memo:'mint '+address,price:'0.02'};await checkNoir(p,{address,transparent},invoice,config());assert.deepEqual(p.calls.at(-1),{method:'zcash_getMaxTransfer',params:[{to,memo:invoice.memo,fundingSource:'transparent',feeTier:'standard'}]});assert(!p.calls.some(x=>x.method==='zcash_sendTransaction'));await assert.rejects(checkNoir(p,{address,transparent},invoice,{...config(),maxFee:'0.00001'}));await assert.rejects(checkNoir(p,{address,transparent},{...invoice,price:'1'},config()));});
test('sending passes exact ZEC decimal amount, shielded payTo, memo and funding source',async()=>{const p=provider();const ticket={config:config(),invoice:{to,memo:'mint '+address,price:'0.02'}};assert.equal(await sendNoir(p,ticket,{address,transparent}),txid);assert.deepEqual(p.calls.at(-1),{method:'zcash_sendTransaction',params:[{to,amount:'0.02',memo:'mint '+address,fundingSource:'transparent'}]});});
test('account changes, stop during account check and expired tasks prevent a send',async()=>{const ticket={config:config(),invoice:{to,memo:'mint '+address,price:'0.02'}};for(const [expected,active,t] of [[{address:'u1'+'c'.repeat(100),transparent},()=>true,ticket],[{address,transparent},()=>false,ticket],[{address,transparent},()=>true,{...ticket,config:{...config(),expiresAt:0}}]]){const p=provider();await assert.rejects(sendNoir(p,t,expected,active));assert(!p.calls.some(x=>x.method==='zcash_sendTransaction'));}});
test('wallet rejects or malformed transaction result never gets retried',async()=>{for(const result of [null,'not-a-txid']){let calls=0;const p={request:async x=>{if(x.method==='zcash_getAccounts')return {shielded:address,transparent};calls++;return result;}};await assert.rejects(sendNoir(p,{config:config(),invoice:{to,memo:'mint '+address,price:'0.02'}},{address,transparent}));assert.equal(calls,1);}});
